import Head from 'next/head'
import CoverSec from '../src/components/topcover/CoverSec'
import Highlight from '../src/components/topcover/Highlight'
import Story from '../src/components/hero-section/Story'
import Tech from '../src/components/Technology/Tech'
import Getour from '../src/components/Getour'
import Industries from '../src/components/Indrusties/Industries'
import Strategy from '../src/components/Strategy/Strategy'
import CareerPromo from '../src/components/Career/CareerPromo'
import Family from '../src/components/Family/Family'



export default function Home() {
  return (
    <>
      <Head>
        <title>Sparrowan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CoverSec/>
        <Highlight/>
        <Story/>
        <Tech/>
        <Getour/>
        <Industries/>
        <Strategy/>
        <Family/>
        <CareerPromo/>
      </main>
    </>
  )
}
